name: Build Android
on:
  push:
    branches:
      - main
      - master
      - jaskaran
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install yarn dependencies
        run: |
          yarn
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Yarn dependencies
        run: |
          yarn
      - name: Gradle Permissions
        run: |
          cd android && chmod +x ./gradlew
      - name: React Native Link
        run: |
          npx react-native link
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: delivery-app-release.apk
          path: android/app/build/outputs/apk/release/
